version: '3'

services:
  db:
    image: postgres:12.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      PGDATA: /pgdata
    volumes:
      - pgdata:/pgdata

  application:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - site-packages:/site-packages
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment: 
      PYTHONUSERBASE: /site-packages
      PATH: $PATH:/site-packages/bin
    tty: true

# volumes defined for use in above configuration
volumes:
  app:
  pgdata:
  site-packages: